url: "https://LudovicRoussel.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ludovic Roussel" # the name of your site, e.g. ACME Corp.
description: "PhD Candidate at the European University Institute (EUI)"
